# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_letter',
            field=models.CharField(db_index=True, editable=False, max_length=1),
        ),
    ]
